{% set name = "keras_mixed_sequence" %}
{% set version = "1.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keras_mixed_sequence-{{ version }}.tar.gz
  sha256: 4d49f4325988dccd9d1f6d1ea53e1fc0be8a4479545387f79db7d9245ed66e91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - numpy
    - tensorflow

test:
  imports:
    - keras_mixed_sequence
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LucaCappelletti94/keras_mixed_sequence
  summary: Lazily loading mixed sequences using Keras Sequence, focused on multi-task models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - isuruf
